# Generated by Django 5.0.6 on 2024-08-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_is_published_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=450, null=True, verbose_name="slug"
            ),
        ),
    ]
