# Generated by Django 5.0.6 on 2024-08-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True,
                help_text="Слаг для создания уникальной ссылки",
                max_length=200,
                null=True,
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
