# Generated by Django 5.0.6 on 2024-08-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="view_counter",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Количество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
