# Generated by Django 5.0.6 on 2024-07-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Введите дату производства товара",
                null=True,
                verbose_name="Дата производства товара",
            ),
        ),
    ]
