# Generated by Django 5.0.6 on 2024-08-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_remove_product_photo_product_image_and_more"),
    ]

    operations = [

        migrations.AddField(
            model_name="product",
            name="view_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Счетчик просмотров товара",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
