# Generated by Django 5.0.6 on 2024-08-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_rename_photo_product_image_product_view_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="view_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
