# Generated by Django 5.0.6 on 2024-08-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_view_counter"),
    ]

    operations = [

        migrations.RemoveField(
            model_name="product",
            name="view_counter",
        ),
    ]
