# Generated by Django 5.0.6 on 2024-08-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_category_category_alter_category_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
        migrations.AddField(
            model_name="product",
            name="view_counter",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Счетчик просмотров"
            ),
        ),
    ]
