# Generated by Django 5.0.6 on 2024-08-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_current",
            field=models.BooleanField(default=True, verbose_name="активная"),
        ),
    ]
